# print('hello \nnigger ')
# a = int(input('age \n'))
# print(a)
# b = input("what is your name ")
# print("Hey " + b)
# print (len(b))
print("Band name gen")
a = input("what is the name of your city\n")
b = input("name of your first pet\n")
print("Name of your bang is "+a+" "+b)